"""empty message

Revision ID: 1e8ac423c238
Revises: c758fc51c815
Create Date: 2018-10-31 13:02:16.408954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8ac423c238'
down_revision = 'c758fc51c815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sec_sport', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('sport', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_sport'), 'user', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sport'), table_name='user')
    op.drop_column('user', 'sport')
    op.drop_column('user', 'sec_sport')
    # ### end Alembic commands ###
