"""first

Revision ID: 9494a4eb730f
Revises: 
Create Date: 2018-09-28 13:15:51.969670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9494a4eb730f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_prefix', sa.String(length=12), nullable=True),
    sa.Column('course_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expertise_course_level'), 'expertise', ['course_level'], unique=False)
    op.create_index(op.f('ix_expertise_course_prefix'), 'expertise', ['course_prefix'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('class_year', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('UserToExpert',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expertise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('expertise', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=560), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['expertise'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_expertise'), 'request', ['expertise'], unique=False)
    op.create_index(op.f('ix_request_timestamp'), 'request', ['timestamp'], unique=False)
    op.create_table('resolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution')
    op.drop_index(op.f('ix_request_timestamp'), table_name='request')
    op.drop_index(op.f('ix_request_expertise'), table_name='request')
    op.drop_table('request')
    op.drop_table('UserToExpert')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_expertise_course_prefix'), table_name='expertise')
    op.drop_index(op.f('ix_expertise_course_level'), table_name='expertise')
    op.drop_table('expertise')
    # ### end Alembic commands ###
